# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-07 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20171107_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 11, 7, 1, 11, 38, 251949, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
